### PR TITLE
Update blockchain data path 

### PR DESCRIPTION
**Pull request by ganz3891**
Update blockchain data path to 
CRYPTONOTE_NAME=Lethean,  
Unix: ~/CRYPTONOTE_NAME/data
Mac: /Library/Application Support/CRYPTONOTE_NAME/data, 
Window: /ProgramData/CRYPTONOTE_NAME/data

### CODE REVIEW

**Review by Snider — COMMENTED** [review]
Wonderful, this PR is perfect.

Could you add a migration step to do this, please? 

`mv OLD NEW`?

**Comment by ganz3891** [comment]
> Wonderful, this PR is perfect.
> 
> Could you add a migration step to do this, please?
> 
> `mv OLD NEW`?

ah sorry , see the message late. Do you mean the below:

1. Detect existence of old folder and data 
2. if yes, ,move (not copy) them to the new location 

Should i consider the scenario if there is already blockchain data at the new location ? For migration , i don't think there should be such a scenario. what do you think?

**Comment by ganz3891** [comment]
Done :
Migration of old block chain data to new block chain data
1. Detect existence of data (data.mdb)
2. if yes, ,move (not copy) them to the new location
3. The log will be with the old name as back up.
If new blockchain data is already there , ignore old blockchain data and issues warning

quicktest

**Review by Snider — COMMENTED** [review]
So, much, better! tyvm.

**Pull request merged**
